const fs = require('fs');

let content = fs.readFileSync('lib/goals.ts', 'utf8');

const replacements = {
  // Goal 1
  "A 'Ways of Working' policy exists including flexible working and hybrid working standards. Formal Flexible Working Requests are handled on a case-by-case basis as per statutory law.": "• Establish a 'Ways of Working' policy including hybrid standards.\n• Handle formal Flexible Working Requests proactively.",
  "Flexibility and available options are proactively mentioned in all job adverts. Senior leaders work hybrid or part-time and are visible role models.": "• Proactively mention flexibility and available options in all job adverts.\n• Ensure senior leaders role-model hybrid or part-time work.",
  "A 'Flexible by Default' culture is adopted; the business must prove a role cannot be flexible rather than the employee proving it can. Disability-related flexibility is an accepted 'Reasonable Adjustment'. Support for menopause and menstrual health is formalised.": "• Adopt a 'Flexible by Default' culture where the business must prove a role cannot be flexible.\n• Accept disability-related flexibility as a 'Reasonable Adjustment'.\n• Formalise support for menopause and menstrual health.",
  "Managers are trained in output-based performance (results over 'presenteeism'). High-spec hardware and ergonomic tools are provided to all remote/hybrid staff. Equitable employee comms, engagement and networking opportunities are guaranteed regardless of location or hours worked.": "• Train managers in output-based performance (results over 'presenteeism').\n• Provide high-spec hardware and ergonomic tools to remote/hybrid staff.\n• Guarantee equitable comms, engagement, and networking regardless of location/hours.",
  "A market-leading approach to ways of working (e.g. 4-day week / 9 day fortnight) is in place. A 'Right to Disconnect' is contractually enforced, protecting employees from 'always-on' culture and burnout. Intersectional uptake data is reviewed monthly by the Board.": "• Implement a market-leading approach to ways of working (e.g. 4-day week or 9-day fortnight).\n• Contractually enforce a 'Right to Disconnect' to protect employees from burnout.\n• Review intersectional uptake data monthly at the Board level.",

  // Goal 2
  "Gender representation is tracked at a high level. A basic commitment to diversity is included in the annual report.": "• Track gender representation at a high level.\n• Include a basic commitment to diversity in the annual report.",
  "The organisation sets internal gender targets. 'Stay and develop interviews' are conducted with women in middle management to understand retention and support progression.": "• Set internal gender targets.\n• Conduct 'Stay and develop interviews' with women in middle management to understand retention and support progression.",
  "Intersectional data is collected. Specific targets are set for women of all backgrounds (Race/Disability/Class/Sexuality) to be represented at all levels. Role profiles are audited to remove class-coded requirements (e.g. university bias).": "• Collect intersectional data and set specific representation targets for women of all backgrounds.\n• Audit role profiles to remove class-coded requirements like university bias.",
  "A formal 'Sponsorship' programme exists where C-suite leaders use their influence to pull marginalised women into high-level rooms. Promotion and interview panels are always diverse, using external advisors where necessary.": "• Create a formal 'Sponsorship' programme where C-suite leaders advocate for marginalised women.\n• Ensure promotion and interview panels are diverse, using external advisors if necessary.",
  "Executive bonuses are directly linked to intersectional diversity outcomes. Radical transparency: External data dashboards measure the 'career velocity' and progression of different demographic groups to drive investment.": "• Directly link executive bonuses to intersectional diversity outcomes.\n• Implement external data dashboards to measure the 'career velocity' of different demographic groups.",

  // Goal 3
  "An executive is named as the EDI lead. A standard anti-harassment policy is in place.": "• Name an executive as the EDI lead.\n• Establish a standard anti-harassment policy.",
  "Mandatory active anti-racism and anti-misogyny training is introduced for managers. Domestic abuse support is included in HR handbooks.": "• Introduce mandatory active anti-racism and anti-misogyny training for managers.\n• Include domestic abuse support in HR handbooks.",
  "Psychological safety is measured via anonymous surveys. ERGs (Employee Resource Groups) are in place and are consulted on policy co-design, including the formal establishment of a dedicated, funded 'Menopause Circle' or peer support network as an active subgroup. A zero-tolerance approach to microaggressions and the 'Preventative Duty' regarding harassment is role-modelled.": "• Measure psychological safety via anonymous surveys.\n• Consult Employee Resource Groups (ERGs) on policy co-design and establish a funded 'Menopause Circle'.\n• Role-model a zero-tolerance approach to microaggressions.",
  "Comprehensive women's health retention plans (Menopause, Fertility, Pregnancy Loss) are active and include specialist coaching, supported by an active Menopause Workplace Risk Assessment Checklist integrated into Health & Safety workflows. Include a specific, mandatory annual module for line managers focusing on navigating conversations, understanding accommodations, and removing performance biases associated with menopause. The Executive Lead presents EDI progress to the Board quarterly with financial-grade rigour.": "• Activate comprehensive women's health retention plans with specialist coaching.\n• Integrate a Menopause Workplace Risk Assessment into Health & Safety workflows.\n• Deliver specific annual line manager training on removing performance biases.\n• Present EDI progress to the Board quarterly.",
  "ERGs are fully funded and have at least 10% formal 'work time' allocated for leaders. The organisation provides independent, third-party reporting lines for harassment and offers paid leave for domestic abuse survivors.": "• Fully fund ERGs and allocate at least 10% formal 'work time' for leaders.\n• Provide independent, third-party reporting lines for harassment.\n• Offer paid leave for domestic abuse survivors.",

  // Goal 4
  "Internal vacancies are posted on staff boards. All staff have development plans in place and regular 121's, additional training is available upon request.": "• Post internal vacancies on staff boards.\n• Ensure all staff have development plans and regular 1-to-1s.",
  "Visual career maps show pathways from entry-level to management. Training is held during core hours and outside school holidays to support those with caring duties.": "• Create visual career maps showing pathways from entry-level to management.\n• Hold training during core hours and outside school holidays to support carers.",
  "Degree requirements are removed from internal roles to support social mobility. The organisation budgets for 'hidden costs' (childcare/travel) to allow lower-paid staff and new employees to attend training and induction.": "• Remove degree requirements from internal roles to support social mobility.\n• Budget for 'hidden costs' (childcare/travel) so lower-paid staff can attend training.",
  "Digital literacy pathways are funded for frontline staff. 'Junior Sponsorship Circles' pair operational staff with senior leaders for advocacy, backed by a structural policy to automatically consider all eligible frontline staff for promotion to eliminate self-nomination barriers. Junior roles are redesigned to attract men into entry roles, balancing occupational segregation. Long term impactful programmes of development are in place for internal women to equitably progress.": "• Fund digital literacy pathways for frontline staff.\n• Establish 'Junior Sponsorship Circles' pairing operational staff with senior leaders.\n• Redesign junior roles to balance occupational segregation and create long-term development programmes.",
  "Social mobility is benchmarked using parental occupation data. 1-to-1 coaching is provided to all women, including 'cultural capital' coaching for women from working-class backgrounds to support their progression into leadership.": "• Benchmark social mobility using parental occupation data.\n• Provide 1-to-1 'cultural capital' coaching for women from working-class backgrounds to support their progression.",

  // Goal 5
  "Statutory Gender Pay Gap reporting is completed. Basic equal pay audits are conducted.": "• Complete statutory Gender Pay Gap reporting.\n• Conduct basic equal pay audits.",
  "Salary bands are published internally. The organisation is an accredited Real Living Wage employer for all staff and contractors.": "• Publish salary bands internally.\n• Become an accredited Real Living Wage employer for all staff and contractors.",
  "Voluntary reporting on Ethnicity and Disability pay gaps. All job adverts must state specific flexible working options, available leave policies (e.g., enhanced parental/caring leave), and a clear salary range (no 'competitive' labels).": "• Report voluntarily on Ethnicity and Disability pay gaps.\n• State specific flexible working options, available leave policies, and clear salary ranges on all job adverts.",
  "Fixed starting salaries are implemented to remove the 'negotiation penalty'. Full employer pension contributions are maintained during the entire duration of all forms of parental leave.": "• Implement fixed starting salaries to remove the 'negotiation penalty'.\n• Maintain full employer pension contributions during all forms of parental leave.",
  "The organisation provides financial management training and support and publishes a time-bound 'Wealth Equity' plan. This addresses the 'motherhood penalty' and the pension gap, assessing the total financial health and long-term security of female employees.": "• Provide financial management training.\n• Publish a time-bound 'Wealth Equity' plan to address the 'motherhood penalty' and pension gap.",

  // Goal 6
  "Hiring managers take annual 'Unconscious Bias' training modules.": "• Ensure hiring managers take annual 'Unconscious Bias' training modules.",
  "Job ads are audited for gendered language. Blind-screening (removing names/universities) is used for all initial CV screening.": "• Audit job ads for gendered language.\n• Implement blind-screening for all initial CV screening.",
  "Interview questions and panel details are shared 48 hours in advance as a default (Neuro-inclusion). 'Cultural fit' scores are replaced with objective, evidence-based rubrics with transparency and decision record keeping.": "• Share interview questions and panel details 48 hours in advance for neuro-inclusion.\n• Replace 'cultural fit' scores with objective, evidence-based rubrics.",
  "Full-funnel data is audited (from application to offer) to identify where marginalised groups 'leak' from the process. Recruitment imagery proactively targets intersectional groups and women over 45.": "• Audit full-funnel data to identify where marginalised groups 'leak' from the process.\n• Use recruitment imagery that proactively targets intersectional groups and women over 45.",
  "AI and peer-audits of performance appraisal language are conducted to ensure objective feedback. All HR systems are fully trans-inclusive and neuro-inclusive by design.": "• Conduct AI and peer-audits of performance appraisal language to ensure objective feedback.\n• Ensure all HR systems are fully trans-inclusive and neuro-inclusive.",

  // Goal 7
  "A women's network exists and holds occasional social or networking events during working hours.": "• Establish a women's network that holds occasional events during working hours.",
  "A formal mentoring programme matches junior staff with senior colleagues. Events are held during core working hours and equitably consider the participation of hybrid and part time staff.": "• Match junior staff with senior colleagues through a formal mentoring programme.\n• Hold events during core working hours to include hybrid and part-time staff.",
  "Women's Network leadership is intersectional (includes Global Majority and Disabled voices - including involvement of external experts if required to bridge any gaps). A dedicated budget is allocated for external coaching for underrepresented women.": "• Ensure Women's Network leadership is intersectional.\n• Allocate a dedicated budget for external coaching for underrepresented women.",
  "Intentional Reverse Mentoring is mandatory for senior leadership. The organisation uses its supply chain influence, requiring contractors to meet WiBC standards to win tenders.": "• Make Intentional Reverse Mentoring mandatory for senior leadership.\n• Use supply chain influence by requiring contractors to meet WiBC standards.",
  "The organisation acts as a 'Sector Leader', publicly sharing EDI failures and learnings. It has established hiring pipelines with grassroots groups and local experts (e.g. disabled women or care leavers) to support the most marginalised women.": "• Act as a 'Sector Leader' by publicly sharing EDI failures and learnings.\n• Establish hiring pipelines with grassroots groups to support the most marginalised women."
};

// Add `guide?: string` to GoalLevel interface
content = content.replace('text: string;', 'text: string;\n  guide?: string;');

// Inject the guides into the levels
for (const [text, guide] of Object.entries(replacements)) {
  const safeText = text.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
  const regex = new RegExp(`(text:\\s*["'\`])(${safeText})(["'\`])`, 'g');
  content = content.replace(regex, `$1$2$3, guide: ${JSON.stringify(guide)}`);
}

fs.writeFileSync('lib/goals.ts', content);
console.log('Successfully updated lib/goals.ts');
